# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       totem-pl-parser

# >> macros
# << macros

Summary:    Totem Playlist Parser library
Version:    2.30.0
Release:    1
Group:      System/Libraries
License:    LGPLv2+
URL:        http://www.gnome.org/projects/totem/
Source0:    http://download.gnome.org/sources/%{name}/2.30/%{name}-%{version}.tar.bz2
Source100:  totem-pl-parser.yaml
Patch0:     fix-automake.patch
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(gmime-2.6)
BuildRequires:  pkgconfig(libxml-2.0)
BuildRequires:  pkgconfig(glib-2.0) >= 2.21.6
BuildRequires:  pkgconfig(gthread-2.0)
BuildRequires:  pkgconfig(gio-2.0) >= 2.24.0
BuildRequires:  gettext
BuildRequires:  perl(XML::Parser)
BuildRequires:  intltool
BuildRequires:  gnome-common

%description
A library to parse and save playlists, as used in music and movie players.

%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
The %{name}-devel package contains libraries and header files for
developing applications that use %{name}.


%prep
%setup -q -n %{name}-%{version}/%{name}

# fix-automake.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
echo "EXTRA_DIST = missing-gtk-doc" > gtk-doc.make
NOCONFIGURE=1 REQUIRED_PKG_CONFIG_VERSION=0.17.1 REQUIRED_AUTOMAKE_VERSION=1.9 USE_GNOME2_MACROS=1 . gnome-autogen.sh --disable-gtk-doc
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%find_lang %{name} --with-gnome

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files -f %{name}.lang
%defattr(-,root,root,-)
# >> files
%doc AUTHORS COPYING.LIB NEWS README
%{_libdir}/*.so.*
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/*
%{_libdir}/*.so
%{_libdir}/pkgconfig/*.pc
#%{_datadir}/gtk-doc/html/totem-pl-parser
# << files devel
